"""migration

Revision ID: 0a6cce07cb4e
Revises: 4752cabcefbf
Create Date: 2025-04-01 18:53:18.679192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a6cce07cb4e'
down_revision = '4752cabcefbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint('ticket_ibfk_1', type_='foreignkey')
        batch_op.drop_column('event_id')
        batch_op.drop_column('original_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('ticket_ibfk_1', 'event', ['event_id'], ['id'])

    # ### end Alembic commands ###
