"""made updates

Revision ID: 4752cabcefbf
Revises: 9f95848e4df1
Create Date: 2025-04-01 17:20:37.146191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4752cabcefbf'
down_revision = '9f95848e4df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resale_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_seller', sa.Boolean(), nullable=False),
    sa.Column('performance_id', sa.Integer(), nullable=False),
    sa.Column('ticket_category', sa.String(length=50), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['performance_id'], ['performance.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ticket_resale')
    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sold_out', sa.Boolean(), nullable=True))

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sound_quality', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('lighting_effects', sa.Integer(), nullable=False))
        batch_op.drop_column('sound_lighting')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('resale_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('ticket_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'visitor', ['owner_id'], ['id'])
        batch_op.drop_column('visitor_id')
        batch_op.drop_column('date_of_availability')
        batch_op.drop_column('available_for_sale')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_for_sale', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_of_availability', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('visitor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ticket_ibfk_4', 'visitor', ['visitor_id'], ['id'])
        batch_op.drop_column('owner_id')
        batch_op.drop_column('resale_status')
        batch_op.drop_column('original_price')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sound_lighting', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('lighting_effects')
        batch_op.drop_column('sound_quality')

    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.drop_column('is_sold_out')

    op.create_table('ticket_resale',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('date_of_interest', sa.DATE(), nullable=False),
    sa.Column('ticket_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('visitor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], name='ticket_resale_ibfk_1'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor.id'], name='ticket_resale_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('resale_queue')
    # ### end Alembic commands ###
