"""migration

Revision ID: 74261cc0afa2
Revises: 0a6cce07cb4e
Create Date: 2025-04-01 18:56:59.029945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74261cc0afa2'
down_revision = '0a6cce07cb4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint('ticket_ibfk_2', type_='foreignkey')
        batch_op.drop_column('festival_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('festival_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('ticket_ibfk_2', 'festival', ['festival_id'], ['id'])

    # ### end Alembic commands ###
