"""fixed

Revision ID: 9f95848e4df1
Revises: 18cc30b2cecf
Create Date: 2025-04-01 16:42:02.877915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f95848e4df1'
down_revision = '18cc30b2cecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('info')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', mysql.TEXT(), nullable=True))

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
